#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Sync to Apache Upstream

# This workflow automatically creates a PR to apache/dubbo-go-pixiu-samples
# when a PR is merged into the main branch of this repository.
#
# Prerequisites:
# - Configure the UPSTREAM_GITHUB_TOKEN secret in repository settings
# - Token should have 'public_repo' permission
# - Recommended: use a dedicated bot account for the token

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

# Explicit permissions required for gh pr comment and gh issue create
permissions:
  contents: read
  pull-requests: write
  issues: write

# Prevent concurrent syncs to avoid conflicts
concurrency:
  group: sync-to-upstream
  cancel-in-progress: false

jobs:
  sync-to-apache:
    name: Sync to Apache Repository
    runs-on: ubuntu-latest

    # Only run when PR is actually merged (not just closed)
    if: github.event.pull_request.merged == true

    steps:
      # Step 1: Checkout code with full history
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.UPSTREAM_GITHUB_TOKEN }}

      # Step 2: Configure Git user
      - name: Configure Git user
        run: |
          git config user.name "Pixiu Bot"
          git config user.email "bot@dubbo-go-pixiu.github.io"

      # Step 3: Add upstream remote and fetch
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/apache/dubbo-go-pixiu-samples.git
          git fetch upstream main

      # Step 4: Create sync branch with timestamp
      - name: Create sync branch
        id: create_branch
        run: |
          SYNC_BRANCH="auto-sync-$(date +%Y%m%d-%H%M%S)"
          echo "SYNC_BRANCH=${SYNC_BRANCH}" >> $GITHUB_ENV
          git checkout -b ${SYNC_BRANCH}
          echo "branch=${SYNC_BRANCH}" >> $GITHUB_OUTPUT

      # Step 5: Rebase onto upstream main
      - name: Rebase onto upstream
        id: rebase
        run: |
          git rebase upstream/main

      # Step 5.5: Remove B-repo specific files
      - name: Remove fork-specific workflow files
        run: |
          # Remove sync workflow files that are specific to B-repo
          # These should not be synced to Apache upstream
          git rm -f .github/workflows/sync-to-upstream.yml || true
          
          # Commit the removal if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: remove fork-specific workflow files
          
            These files are specific to dubbo-go-pixiu/dubbo-go-pixiu-samples organization fork
            and are not needed in the upstream Apache repository.
          
            Files removed:
            - .github/workflows/sync-to-upstream.yml
            - .github/workflows/SYNC_WORKFLOW_GUIDE.md"
          fi

      # Step 6: Push sync branch to origin
      - name: Push sync branch
        run: |
          git push origin ${SYNC_BRANCH} --force-with-lease

      # Step 7: Generate PR body with attribution
      - name: Generate PR description
        id: pr_body
        env:
          ORIGINAL_BODY: ${{ github.event.pull_request.body }}
        run: |
          ORIGINAL_AUTHOR="${{ github.event.pull_request.user.login }}"
          ORIGINAL_PR="${{ github.event.pull_request.number }}"
          ORIGINAL_URL="${{ github.event.pull_request.html_url }}"
          MERGED_AT="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          
          {
            echo "## 🔄 Upstream Sync from Community Fork"
            echo ""
            echo "This PR automatically syncs changes from the community fork to the Apache upstream repository."
            echo ""
            echo "### Original Contribution"
            echo ""
            echo "- **Author**: @${ORIGINAL_AUTHOR}"
            echo "- **Original PR**: ${ORIGINAL_URL}"
            echo "- **Merged at**: ${MERGED_AT}"
            echo ""
            echo "### Original PR Description"
            echo ""
            echo "---"
            echo ""
            echo "${ORIGINAL_BODY}"
            echo ""
            echo "---"
            echo ""
            echo "### Commit Details"
            echo ""
            echo "All commits in this PR preserve the original authorship. You can verify this by checking the commit history."
            echo ""
            echo "**Note**: This PR was automatically created by GitHub Actions when PR #${ORIGINAL_PR} was merged into \`dubbo-go-pixiu/dubbo-go-pixiu-samples:main\`."
            echo ""
            echo "cc @${ORIGINAL_AUTHOR}"
          } > pr_body.md
          
          echo "Generated PR body"

      # Step 8: Create PR to Apache upstream
      - name: Create PR to apache/dubbo-go-pixiu-samples
        id: create_pr
        env:
          GH_TOKEN: ${{ secrets.UPSTREAM_GITHUB_TOKEN }}
          SYNC_PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          PR_URL=$(gh pr create \
            --repo apache/dubbo-go-pixiu-samples \
            --base main \
            --head dubbo-go-pixiu:${SYNC_BRANCH} \
            --title "$SYNC_PR_TITLE" \
            --body-file pr_body.md)
          
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT
          echo "✅ Successfully created PR: ${PR_URL}"

      # Step 9: Comment on original PR with upstream PR link
      - name: Notify original PR
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          UPSTREAM_PR_URL: ${{ steps.create_pr.outputs.pr_url }}
        run: |
          # Generate comment body and post to original PR
          {
            echo "🤖 **Automated Upstream Sync**"
            echo ""
            echo "Your PR has been automatically synced to Apache upstream:"
            echo "$UPSTREAM_PR_URL"
            echo ""
            echo "Thank you for your contribution! 🎉"
          } > comment_body.md
          
          # Post comment to the PR in the base repository
          gh pr comment "$PR_NUMBER" --repo dubbo-go-pixiu/dubbo-go-pixiu-samples --body-file comment_body.md || {
            echo "⚠️  Failed to comment on PR #${PR_NUMBER}, but upstream sync succeeded"
            echo "Upstream PR: $UPSTREAM_PR_URL"
            exit 0
          }

      # Step 10-11: Error handling for rebase conflicts
      - name: Handle rebase failure
        if: failure() && steps.rebase.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          git rebase --abort || true
          
          gh issue create \
            --repo dubbo-go-pixiu/dubbo-go-pixiu-samples \
            --title "⚠️ Failed to auto-sync PR #${PR_NUMBER} to upstream" \
            --body "## Sync Failure Report
          
            **Original PR**: #${PR_NUMBER}
            **Author**: @${PR_AUTHOR}
            **Error**: Rebase conflicts detected when syncing to apache/dubbo-go-pixiu-samples
          
            ### Action Required
          
            Manual intervention is needed to resolve conflicts and create the upstream PR.
          
            ### Steps to resolve:
          
            1. Checkout the main branch
            2. Create a new branch: \`git checkout -b manual-sync-${PR_NUMBER}\`
            3. Add upstream: \`git remote add upstream https://github.com/apache/dubbo-go-pixiu-samples.git\`
            4. Fetch upstream: \`git fetch upstream main\`
            5. Rebase: \`git rebase upstream/main\`
            6. Resolve conflicts manually
            7. Push and create PR to apache/dubbo-go-pixiu-samples
          
            cc @${PR_AUTHOR}" \
            --label "sync-failure,needs-attention"
          
          echo "❌ Rebase failed. Issue created for manual resolution."

